---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: compose-data-redis-volume-ENVSTYLE
  labels:
    app: compose-redis-ENVSTYLE
    env: ENVSTYLE
    username: USERNAME
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi