---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: compose-data-redis-volume
  labels:
    app: compose
    env: test
    username: astacc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi