---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: compose-worker-ENVSTYLE
  labels:
    app: compose-worker-ENVSTYLE
    env: ENVSTYLE
    username: USERNAME
spec:
  replicas: WRKREP
  selector:
    matchLabels:
      app: compose-worker-ENVSTYLE
  template:
    metadata:
      labels:
        app: compose-worker-ENVSTYLE
        env: ENVSTYLE
        username: USERNAME
    spec:
      containers:
        - name: compose-worker-ENVSTYLE
          imagePullPolicy: Always
          image: akhilsadam/compose-worker:0.0.2
          command: ['python3']
          args: ['-u', 'worker.py', ip_address]
          ports:
          - name: http
            containerPort: 5026
          volumeMounts:
            - name: compose-data-flask-volume-ENVSTYLE
              mountPath: "/app/app/static/audio"
      volumes:
        - name: compose-data-flask-volume-ENVSTYLE
          persistentVolumeClaim:
            claimName: compose-data-flask-volume-ENVSTYLE