---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: compose-flask-ENVSTYLE
  labels:
    app: compose-flask-ENVSTYLE
    env: ENVSTYLE
    username: USERNAME
spec:
  replicas: APIREP
  selector:
    matchLabels:
      app: compose-flask-ENVSTYLE
  template:
    metadata:
      labels:
        app: compose-flask-ENVSTYLE
        env: ENVSTYLE
        username: USERNAME
    spec:
      containers:
        - name: compose
          imagePullPolicy: Always
          image: akhilsadam/compose:0.0.2
          command: ['python3']
          args: ['-u', 'core.py', ip_address, PROXY]
          ports:
          - name: http
            containerPort: 5026
          volumeMounts:
            - name: compose-data-flask-volume-ENVSTYLE
              mountPath: "/app/app/static/audio"
      volumes:
        - name: compose-data-flask-volume-ENVSTYLE
          persistentVolumeClaim:
            claimName: compose-data-flask-volume-ENVSTYLE