---
apiVersion: v1
kind: Service
metadata:
  name: compose-flask-service
  labels:
    app: compose-flask-service
    env: test
    username: astacc
spec:
  type: ClusterIP
  selector:
    app: compose-flask
    env: test
    username: astacc
  ports:
  - name: http
    port: 5000
    targetPort: 5026