---
apiVersion: v1
kind: Service
metadata:
  name: compose-redis-service-ENVSTYLE
  labels:
    app: compose-redis-service-ENVSTYLE
    env: ENVSTYLE
    username: USERNAME
spec:
  type: ClusterIP
  selector:
    app: compose-redis-ENVSTYLE
    env: ENVSTYLE
    username: USERNAME
  ports:
  - name: http
    port: 6379
    targetPort: 6379