---
apiVersion: v1
kind: Service
metadata:
  name: compose-flask-service-ENVSTYLE
  labels:
    app: compose-flask-service-ENVSTYLE
    env: ENVSTYLE
    username: USERNAME
spec:
  type: ClusterIP
  selector:
    app: compose-flask-ENVSTYLE
    env: ENVSTYLE
    username: USERNAME
  ports:
  - name: http
    port: 5000
    targetPort: 5026