---
apiVersion: v1
kind: Service
metadata:
  name: compose-nodeport-service
  labels:
    app: compose-nodeport-service
    env: ENVSTYLE
    username: astacc
spec:
  type: NodePort
  selector:
    app: compose-flask
    env: ENVSTYLE
    username: astacc
  ports:
  - name: http
    port: 5026
    targetPort: 5026
    nodePort: NODEPORT