---
apiVersion: v1
kind: Service
metadata:
  name: compose-nodeport-service-ENVSTYLE
  labels:
    app: compose-nodeport-service-ENVSTYLE
    env: ENVSTYLE
    username: USERNAME
spec:
  type: NodePort
  selector:
    app: compose-flask-ENVSTYLE
    env: ENVSTYLE
    username: USERNAME
  ports:
  - name: http
    port: 5026
    targetPort: 5026
    nodePort: NODEPORT