---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: compose-data-redis-volume-test
  labels:
    app: compose-redis-test
    env: test
    username: astacc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi
